CREATE DATABASE IF NOT EXISTS api_database;

USE api_database;

CREATE TABLE albums(
	id INT PRIMARY KEY AUTO_INCREMENT,
	release_date DATE,
	category_id INT,
	title VARCHAR(255),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE categories(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(10),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
